### PR TITLE
Fix/1.x/79 no link to root

### LINKED ISSUE #79: No link to root of publication in menu
In the publication menu, there is no link to the top level root publication page.

Image

Feels like there should be, no?

### PR DESCRIPTION
**Pull request by rupertj**
Fixes #79

### CODE REVIEW

**Comment by rupertj** [comment]
Screenshot 2023-11-02 at 09 56 16

I've made a fix for this. Here's a screenshot of what it looks like.

**Comment by finnlewis** [comment]
@rupertj Fresh install on this branch. 

Create a new publication page: 

```
Warning: Trying to access array offset on value of type null in localgov_publications_tokens_alter() (line 26 of modules/contrib/localgov_publications/localgov_publications.tokens.inc).

localgov_publications_tokens_alter(Array, Array, Object) (Line: 545)
Drupal\Core\Extension\ModuleHandler->alter('tokens', Array, Array, Object) (Line: 373)
Drupal\Core\Utility\Token->generate('node', Array, Array, Array, Object) (Line: 241)
Drupal\Core\Utility\Token->doReplace(1, '[node:title] | [site:name]', Array, Array, Object) (Line: 191)
Drupal\Core\Utility\Token->replace('[node:title] | [site:name]', Array, Array, NULL) (Line: 66)
Drupal\metatag\MetatagToken->replace('[node:title] | [site:name]', Array, Array) (Line: 768)
Drupal\metatag\MetatagManager->processTagValue(Object, Array, Array, , 'en') (Line: 614)
Drupal\metatag\MetatagManager->generateRawElements(Array, Object) (Line: 550)
Drupal\metatag\MetatagManager->generateElements(Array, Object) (Line: 524)
metatag_get_tags_from_route() (Line: 278)
_metatag_remove_duplicate_entity_tags(Array) (Line: 220)
metatag_entity_view_alter(Array, Object, Object) (Line: 545)
Drupal\Core\Extension\ModuleHandler->alter('node_view', Array, Object, Object) (Line: 304)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 238)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 797)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 386)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 204)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 238)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 592)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 239)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 128)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 186)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by finnlewis** [comment]
@rupertj fixed that warning with https://github.com/localgovdrupal/localgov_publications/pull/96/commits/e260406df053b5a267a5805ff2de5dfe87625981

The situation arises when you create a publication page but do not put it in a book, which I guess is very possible for a single page publication.

**Review by finnlewis — APPROVED** [review]
Works for me, thanks @rupertj !

**Comment by rupertj** [comment]
Cool. Thanks for testing :)

**Pull request merged**
