### PR TITLE
Fixes issue where publication navigation block shows up on a single page publication.

### PR DESCRIPTION
**Pull request by rupertj**
Fix for #190

### CODE REVIEW

**Comment by rupertj** [comment]
@AWearring Any chance you could give this change a review and confirm it fixes the issue for you? Ta.

**Comment by AWearring** [comment]
@rupertj I've installed this branch and can confirm that this has resolved the issue I was seeing

**Review by AWearring — APPROVED** [review]
Tested and issue  has been resolved https://github.com/localgovdrupal/localgov_publications/issues/190

**Comment by rupertj** [comment]
Super. Thankyou!

**Pull request merged**
