### PR TITLE
Fixes for incorrect breadcrumbs.

### PR DESCRIPTION
**Pull request by rupertj**
Fixes for #201

### CODE REVIEW

**Comment by rupertj** [comment]
To explain what's going on in this PR...

It's a fix for an issue that Sarah from Blackburn & Darwen ran into, where having set a publication under another page in the URL structure, the URL aliases were incorrect and the breadcrumbs were missing.

There's two parts for this fix:

1) Instead of using the BookBreadcrumbBuilder for publications, this adds a new BreadCrumbBuilder specifically for publications that extends the default PathBasedBreadcrumbBuilder and makes breadcrumbs in publications work like they do in other content.

2) Change the pathauto pattern for publication pages. The old pattern used a token that worked fine if you stuck to the defaults, but if you changed the URL alias of the root publication page, none of the pages under it would pick that up. I've added a new token that builds the path to a publication page out of three separate components: the cover page alias if there is one, the alias of the root publication page and any other pages in the publication in the hierarchy between the current page and the root.

The code works and has decent test coverage, so I'm confident this'll work for new installs. I think it needs some testing on existing installs to check that it doesn't have any unforseen consequences for existing publications though.

**Comment by ekes** [comment]
> The code works and has decent test coverage, so I'm confident this'll work for new installs.

I've not had time to manually test, but am happy that the automated tests are there for what is expected.

**Comment by rupertj** [comment]
I've installed this in my local copy of H&F's site, and I'm happy it didn't break anything there.

I'd still like someone else to test on a site with some existing publications, ideally. I'd suggest the following test plan:
* Install this branch of the module ("localgovdrupal/localgov_publications": "dev-fix/1.x/201-incorrect-breadcrumbs as 1.0.8" in composer, then composer update)
* Run updates (drush updb)
* View an existing publication, check URL alias and breadcrumbs.
* Edit an existing page, check URL alias and breadcrumbs.
* Add a new page to an existing publication, check URL alias and breadcrumbs.
* Ideally repeat the steps above on a publication with a cover page, and one without.
* Edit the URL alias of a cover page to put it under another page in the site's structure. Every other page in the publication should have its URL alias and breadcrumbs updated to follow this change.

**Comment by AWearring** [comment]
@rupertj 
Using your test plan I found no issues on a copy of my local West Lindsey Test site. However, I did find an issue when changing the URL Alias of a Publication that doesn't have an associated cover page. When this URL is changed it child pages don't have their URLs updated, unless performing an edit and save on each individual child page.

**Comment by rupertj** [comment]
I've added issue #207 to cover that. It's not something the module's meant to do at the moment, but it does feel like a bit of an omission...

**Pull request merged**
