### PR TITLE
Removed dependency on ck4 via patch to footnotes module. Changed install config for supplied editor to use ck5.

### LINKED ISSUE #95: Dependancy on ckeditor4?
Not sure the reasoning here, but maybe this isn't something that should be forced, is there some compatability reasons?

### PR DESCRIPTION
**Pull request by rupertj**
Fixes #95

### CODE REVIEW

**Comment by andybroomfield** [comment]
Thanks @rupertj 
I'm still seeing ckeditor download, but seeing as that is not removed in composer.json in the patch I guess that is expected.
I am seeing the following error when trying to use footnotes in CKeditor 5 (which is presumably why there is a CKeditor 4 dependancy?

> Warning: Undefined array key 0 in Drupal\footnotes\Plugin\Filter\FootnotesFilter->getLinkInstances() (line 393 of modules/contrib/footnotes/src/Plugin/Filter/FootnotesFilter.php).
Drupal\footnotes\Plugin\Filter\FootnotesFilter->getLinkInstances('Fore overhaul landlubber or just lubber mizzenmast lugsail topsail Spanish Main killick six pounders hang the jib. Jack Tar scourge of the seven seas yawl handsomely long boat bilged on her anchor swab parley sheet six pounders. Lass wherry doubloon no prey, no pay sutler Sail ho Sea Legs transom long clothes port.
Clap of thunder nipper doubloon snow lugsail reef sails Sea Legs rope's end pirate dance the hempen jig. Hulk Gold Road Privateer fluke careen haul wind knave maroon bilge water hogshead. Port cutlass Shiver me timbers long clothes gun yard hempen halter barque long boat scourge of the seven seas.
Jib shrouds lookout starboard case shot   black jack rigging scourge of the seven seas aft. Black spot lee avast deadlights furl me carouser driver gunwalls hail-shot. Rutters carouser lugsail broadside belaying pin ye Jolly Roger hempen   black jack.
') (Line: 117)
Drupal\footnotes\Plugin\Filter\FootnotesFilter->process('Fore overhaul landlubber or just lubber mizzenmast lugsail topsail Spanish Main killick six pounders hang the jib. Jack Tar scourge of the seven seas yawl handsomely long boat bilged on her anchor swab parley sheet six pounders. Lass wherry doubloon no prey, no pay sutler Sail ho Sea Legs transom long clothes port.
Clap of thunder nipper doubloon snow lugsail reef sails Sea Legs rope's end pirate dance the hempen jig. Hulk Gold Road Privateer fluke careen haul wind knave maroon bilge water hogshead. Port cutlass Shiver me timbers long clothes gun yard hempen halter barque long boat scourge of the seven seas.
Jib shrouds lookout starboard case shot   black jack rigging scourge of the seven seas aft. Black spot lee avast deadlights furl me carouser driver gunwalls hail-shot. Rutters carouser lugsail broadside belaying pin ye Jolly Roger hempen   black jack.
', 'en') (Line: 118)

**Comment by finnlewis** [comment]
Thanks @rupertj  - we'll try to test it soon

**Comment by agile-simon** [comment]
@rupertj - can confirm I'm seeing the same behaviour as Andy.

`Warning: Undefined array key 0 in Drupal\footnotes\Plugin\Filter\FootnotesFilter->getLinkInstances() (line 388 of modules/contrib/footnotes/src/Plugin/Filter/FootnotesFilter.php). `

Also, not sure if the switch from paratest to phpunit in github workflow was intentional?

**Comment by finnlewis** [comment]
@rupertj sounds like this isn't quite working as intended. You got time this week to look at it again?

**Comment by rupertj** [comment]
> Also, not sure if the switch from paratest to phpunit in github workflow was intentional?

This was intentional. Paratest wasn't handling unit test failure properly, which was getting annoying. For example:
https://github.com/localgovdrupal/localgov_publications/actions/runs/7047889712/job/19182842344

This is actually one of the unit tests failing, but instead of getting the test fail message, that error shows up.

Using PHPUnit instead of Paratest shows the test failure properly:
https://github.com/localgovdrupal/localgov_publications/actions/runs/7048357873/job/19184413130

**Comment by rupertj** [comment]
I'm closing this PR in favour of #126.

Please see issue #124 for my reasoning.

**Pull request closed without merging**
