### PR TITLE
Added hook_modules_installed() to immediately delete the book node type when book module is installed.

### PR DESCRIPTION
**Pull request by rupertj**
…pe when book module is installed.

### CODE REVIEW

**Comment by rupertj** [comment]
I'm testing this now:
- [x] Book page type isn't present if publications is enabled when book isn't.
- [x] Book page type is present if publications is enabled when book is.
- [x] Book page type isn't present if publications is enabled when book isn't, via config import.
- [x] Book page type is present if publications is enabled when book is, via config import.

**Comment by finnlewis** [comment]
Thanks @rupertj !

@andybroomfield would you be able to test this? I know you use book module, so you're well placed to confirm this does not have any unintended consequences.

**Comment by joachim-n** [comment]
I don't understand why this is a different PR?

EDIT: NM, saw comment on slack.

**Comment by finnlewis** [comment]
@andybroomfield might you be able to give this a quick test on your site?

**Review by finnlewis — APPROVED** [review]
Tested locally and works for me.

If do nit already have book module installed, I don't get the book content type.

If I already have book module installed, the book content types sticks around.

Great!

I'd still love for @andybroomfield to test it on the BHCC site if possible.

**Review by andybroomfield — APPROVED** [review]
It's fine from me, though we have a different content type not book.

**Comment by rupertj** [comment]
Excellent. Thanks both!

**Pull request merged**
