### PR TITLE
Feature/1.x/13 publication landing frontend

### PR DESCRIPTION
**Pull request by rupertj**

### CODE REVIEW

**Comment by finnlewis** [comment]
@justinepocock wants to do a little more work on this before merging :smile:

**Comment by finnlewis** [comment]
@justinepocock @rupertj where are we at with this one?

**Comment by justinepocock** [comment]
Here feels about right: https://media.giphy.com/media/Z9ErMP3gYYlcAadEGd/giphy.gif

**Comment by finnlewis** [comment]
Waiting for these :

- [ ] https://github.com/localgovdrupal/localgov_publications/issues/75 
- [ ] https://github.com/localgovdrupal/localgov_publications/issues/7

**Comment by finnlewis** [comment]
@justinepocock @rupertj need any help here Nearly ready to merge this one?

**Comment by justinepocock** [comment]
Let's just get this merged, the only thing outstanding really is the svg for excel files which for some reason is proving more tricky than expected. It feels like a very small thing to be blocking this.

**Pull request merged**
