### PR TITLE
Added layout paragraphs to publication content types instead of existing content fields.

### PR DESCRIPTION
**Pull request by rupertj**
Implements #74

### CODE REVIEW

**Comment by finnlewis** [comment]
Looking at the config dependency errors @rupertj , I think we might need to require layout_paragraphs in composer.json

**Comment by rupertj** [comment]
Yeah, you're probably right. Cheers for spotting that, although I wasn't expecting anyone to review this yet :)

**Comment by finnlewis** [comment]
Hey @rupertj  - sorry, no worries!

I'm just taking advantage of Merge Mondays moving to Merge Tuesdays... so rattle through the list of pull requests at 

https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Alocalgovdrupal+draft%3Afalse

We also can mark pull requests as draft if we want to do more work before review, then they don't show up in that list.

**Comment by rupertj** [comment]
@finnlewis Tests are green, and my own manual testing looks good. Could you give this a look? Ta.

**Comment by finnlewis** [comment]
Testing now! Sorry not to get to it sooner @rupertj

**Pull request merged**
