### PR TITLE
Added form validation to ensure that publication pages are always in a book.

### PR DESCRIPTION
**Pull request by rupertj**
Fix for #33

### CODE REVIEW

**Comment by finnlewis** [comment]
@agile-simon fancy testing this one?

**Comment by finnlewis** [comment]
@agile-simon might you have time to review this? 

Or @stephen-cox are you back yet? :smile:

**Review by agile-simon — APPROVED** [review]
Code looks fine, tested locally and works as expected. Arguably don't need a 'please in the error message per GDS guidelines, not sure how consistently that is applied though.

**Comment by rupertj** [comment]
Great - thanks Simon!

**Pull request merged**
