### PR TITLE
Add the node title to the top of the current node if it's a child page of a publication.

### PR DESCRIPTION
**Pull request by rupertj**

### CODE REVIEW

**Comment by zumbawithfinn** [comment]
@rupertj I think I'm still getting the same error locally when creating a new publication: 


`> Message | TypeError: localgov_publications_node_view(): Argument #2 ($entity) must be of type EntityInterface, Drupal\node\Entity\Node given in localgov_publications_node_view() (line 184 of /var/www/html/web/modules/contrib/localgov_publications/localgov_publications.module) `

**Comment by rupertj** [comment]
@zumbawithfinn Did you pull the code just now? I just pushed a fix.

**Comment by rupertj** [comment]
Although the tests are still failing in the CI, which is odd.

**Comment by rupertj** [comment]
It's not odd. I just didn't fix it properly the first time. Although the brief has changed in the meeting we just had, so don't merge this.

**Pull request closed without merging**
